name: CD - Deploy to EKS

on:
  workflow_run:
    workflows: [ "CI - Build and Scan" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name demo-eks

      # - name: Replace image in manifest
      #   env:
      #     ECR_REPO: ${{ secrets.ECR_REPOSITORY }}
      #   run: |
      #     IMAGE_TAG=${{ github.run_number }}
      #     sed -i "s|REPLACE_IMAGE|$ECR_REPO:$IMAGE_TAG|g" app/deployment.yaml

            
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
                  
      - name: Update & Deploy to EKS
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          echo "Using ECR Repo: $ECR_REPOSITORY"
          sed -i "s|REPLACE_IMAGE|$ECR_REPOSITORY:${{ github.event.workflow_run.run_number }}|g" app/deployment.yaml
      
          # Deploy the updated manifest
          kubectl apply -f app/deployment.yaml -n default
          kubectl apply -f app/service.yaml -n default
          kubectl rollout status deployment/npm-app -n default
          # Revert deployment.yaml back to original so repo is clean
          git checkout -- app/deployment.yaml
      
          # Commit only if needed for audit trail (optional)
          git config user.name "jadalaramani"
          git config user.email "jadalaramani@gmail.com"
          git add .
          git commit -m "Deployed image version ${{ github.run_number }} [skip ci]" || echo "No changes to commit"
          git push

